title: thedersen.com
url: http://thedersen.com
permalink: /blog/:year/:month/:day/:title/
feed_url: http://feeds.feedburner.com/thedersen

markdown: rdiscount
pygments: true

google_analytics_tracking_id: UA-12325477-1
disqus_short_name: thedersen
twitter_user: thedersen